// Code generated by "stringer -type=Method"; DO NOT EDIT.

package http

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GET-0]
	_ = x[HEAD-1]
	_ = x[POST-2]
	_ = x[PUT-3]
	_ = x[DELETE-4]
	_ = x[CONNECT-5]
	_ = x[OPTIONS-6]
	_ = x[TRACE-7]
	_ = x[PATCH-8]
}

const _Method_name = "GETHEADPOSTPUTDELETECONNECTOPTIONSTRACEPATCH"

var _Method_index = [...]uint8{0, 3, 7, 11, 14, 20, 27, 34, 39, 44}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
